### ISSUE TITLE
Lost the tooltips and Conviction Growth Graph

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#223]
- [x] Tooltips went away on the table
![Screen Shot 2021-11-18 at 5 41 08 PM](https://user-images.githubusercontent.com/14945613/142514125-31e7e9b0-be39-4924-bb3f-3c78b9ab489f.png)

- [ ] What happened to that sexy CV growth graph?
![Screen Shot 2021-11-18 at 7 15 49 PM](https://user-images.githubusercontent.com/14945613/142528572-c676e9b9-0c91-4bb2-a467-47ca7833f029.png)

**Comment by pkretzschmar** [comment]
@GriffGreen the tooltips that we had on this table was to explain the variable and scenarios (older headers). After we transpose the table, we lost it because was not making any sense. If someone can create new tooltips text for the new headers, I can implement it.

Regarding the Chart, I removed because it was suffering from a few bugs, but I already working on it

**Comment by divine-comedian** [comment]
@pkretzschmar  tooltips added in to develop branch
